from .combat.combat import OSRSCombat
from .chinchompas import Chinchompas
from .fletching import Fletching
from .gotr import Gotr
from .string_bow import String_Bow
from .tithe_farm import Tithe_Farm
from .crafting_bracelets import Crafting_Bracelets
from .enchant_diamond import Enchant_Bracelet
from .alching import Alching